function plot_figure_regcoef_outcomedif(addr,colors)

%1=partial, 2=complete

choice{1}   = load([addr.glme filesep 'glme_regret_onchoice_switch_Partial' ]);
choice{2}   = load([addr.glme filesep 'glme_regret_onchoice_switch_Complete']);

rt{1}       = load([addr.glme filesep 'glme_regret_onrt_switch_Partial' ]);
rt{2}       = load([addr.glme filesep 'glme_regret_onrt_switch_Complete']);

%%
regs = [2];
coef_names      = choice{1}.glme.CoefficientNames;

coef_est(:,1)   = choice{1}.glme.Coefficients.Estimate(regs) * -1;
coef_est(:,2)   = choice{2}.glme.Coefficients.Estimate(regs) * -1;

coef_pval(:,1)  = choice{1}.glme.Coefficients.pValue(regs);
coef_pval(:,2)  = choice{2}.glme.Coefficients.pValue(regs);

f = figure; 

% x = [1,2];
b_odif1 = bar(1,coef_est(1,1));
hold on
b_odif2 = bar(2,coef_est(1,2));

set(b_odif1, ...
    'FaceColor', colors.Partial.real.A2.face, ... 
    'LineWidth', 1, ... 
    'BarWidth',  0.8); 

set(b_odif2, ...
    'FaceColor', colors.Complete.real.A2.face, ... 
    'LineWidth', 1, ... 
    'BarWidth',  0.8); 



hold on

for i = 1:2
if coef_pval(1,i) <= 0.05

p_pval = plot(i,coef_est(1,i) + 0.025);

set(p_pval, ...
    'LineStyle',            'none', ...
    'Marker',               '*', ...
    'MarkerSize',            7, ...
    'Color',                'r'); 
end

end

set(gca, ...
  'Box'         , 'on'     , ...
  'TickDir'     , 'in'     , ...
  'TickLength'  , [.005 .005] , ...
  'XMinorTick'  , 'off'     , ...
  'YMinorTick'  , 'off'     , ...
  'XColor'      , [.3 .3 .3], ...
  'YColor'      , [.3 .3 .3], ...
  'XTick'       , 0:1:3     , ...
  'YTick'       , 0:0.1:1   , ...
  'XGrid'       , 'off'     , ...
  'YGrid'       , 'off'      , ...
  'XLim'        , [0 3]     , ...
  'YLim'        , [0 1]     , ...
  'XTick'       , []        , ...
  'LineWidth'   , 1         );



% disp(glme);
disp('oops');

%%